spring:
  application:
    name: VApp

  datasource:
    url: jdbc:postgresql://localhost:5432/VApp
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true